[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[redirects]]
  from = "/config.json"
  to = "/.netlify/functions/public-config"
  status = 200
